### PR TITLE
Fix ScopeBuilder persistence/serialization

### LINKED ISSUE #1843: ScopeBuilder must support load/save
demo https://dev.agiletoolkit.org/demos/form-control/scope-builder.php

Currently it outputs `Unexpected non-scalar value` on Save.

### PR DESCRIPTION
**Pull request by mvorisek**
fixes https://github.com/atk4/ui/issues/1843

support was removed/disabled in https://github.com/atk4/ui/pull/1667/files#r720693272

### CODE REVIEW

**Comment by mvorisek** [comment]
sponsors welcomed, I do not use ScopeBuilder and fixing is not trivial

**Comment by mkrecek234** [comment]
@mvorisek I pushed now the ScopeBuilder with the old demo and behat tests, uncommented the respective scopebuilder test line. Could you review the behat test as it is not passing either?

**Comment by mvorisek** [comment]
In https://github.com/atk4/ui/issues/1843#issuecomment-2011838281 I have told you to not bother with unrelated stuff now, fix unserialization first, then it is your task to make it passing the CI.

**Comment by mvorisek** [comment]
backup before branch delete: https://github.com/atk4/ui/compare/develop...0de874d2f6

**Pull request closed without merging**
