### PR TITLE
add CRUD hooks "pageCreateInit" and "pageUpdateInit"

### PR DESCRIPTION
**Pull request by romaninsh**
Currently it's difficult to execute UI code for the CRUD when "add" or "edit" modal windows open. This PR adds "Hooks" for the CRUD to perform those changes:

``` php
$crud = $app->add('CRUD');
$crud->addHook('pageCreateInit', function($crud, $form) {
    $form->getField('name')->on('click')->hide();
});
$crud->setModel(new User($app->db));
```

Clicking on the name field will hide it:

image

Here is a more advanced example of replacing dropdown values through a callback:

```
$crud->addHook('pageCreateInit', function($crud, $form) {

        
    $country_select = $form->getField('country_id');
    $city_select = $form->getField('city_id');

    $expr = [
        function($t) use ($city_select, $country_select) {
            return [
                $city_select->js()->dropdown(
                    'change values', 
                    $_POST['country_id'] ?
                         $country_select->model
                             ->load($_POST['up_id'])
                             ->ref('Cities') : 
                    []),
                 $city_select->js()->removeClass('loading')
            ];
        },
        $city_select->js()->dropdown('clear'),
        $city_select->js()->addClass('loading'),
    ];

    $country_select->onChange($expr, ['args' => [
        'country_id' => $country_select->jsInput()->val()
    ]]);
});
```

### CODE REVIEW

**Comment by ibelar** [comment]
@romaninsh - Can we pass an extra arguments to hooks? 

Instead of having to define two callbacks, one for update and one for create, we could simply have one callback that receive the form and the mode.
```
// for pageCreate
 $this->hook('onPageSetup', [$this->formCreate, 'create']);
//for pageUpdate
 $this->hook('onPageSetup', [$this->formUpdate, 'update']);
```
I believe the two forms will be setup identically most of the time so defining only one callback instead of two. But we still have choice of setting up createForm and updateForm differently if needed.

**Comment by gowrav-vishwakarma** [comment]
A much needed Update :)

**Comment by DarkSide666** [comment]
Looks fine with me.

**Comment by romaninsh** [comment]
I'd like to hold off on this while considering: https://github.com/atk4/data/pull/442

**Pull request closed without merging**
