### PR TITLE
[fix] registerExecutor parameter type

### PR DESCRIPTION
**Pull request by ibelar**
Allow using Object instance as seed.

### CODE REVIEW

**Review by mvorisek — APPROVED** [review]

**Comment by mvorisek** [comment]
merged but the seed object is not instanced neewly, thus allowing object seed in general may lead to very strange results, be careful

**Comment by ibelar** [comment]
Is it better to check for proper instance then and throw error if not array and not of type ExecutorInterface?

**Comment by mvorisek** [comment]
Phpstan will do this check if enabled in project where used.

The issue is when you pass some object seed, that is expected to be instanced for every use.

**Comment by ibelar** [comment]
yes right, I misunderstood your comment. Perhaps check should be at the object creation in order to make sure the created instance if of type ExecutorInterface.

**Pull request merged**
