### PR TITLE
Delete agileui.js

### PR DESCRIPTION
**Pull request by mvorisek**
Old stale file, use can create if needed.

WARNING: This PR is to test the feedback, need more work.

### CODE REVIEW

**Comment by romaninsh** [comment]
Isn't it needed? Could we create it for release / demo?

**Comment by mvorisek** [comment]
Your friends with help you to decide if this is $0 worth or not!

**Comment by DarkSide666** [comment]
I think this file wasn't needed and probably can/should be removed.
But let @ibelar review this.

**Comment by ibelar** [comment]
Sure this can be deleted. Not use anymore. Behat test setup would need to remove compression of this file as well.

**Comment by acicovic** [comment]
So since @ibelar said this can be deleted, perhaps we should go forward and merge this?

**Comment by ibelar** [comment]
@acicovic - Better need to wait. There are still work need to be done on this PR. Behat test setup need to be check. I will set it up as draft for now.

**Comment by romaninsh** [comment]
Wouldn't that break menu?

**Comment by ibelar** [comment]
@romaninsh - No. Side menu does not rely on this file anymore.

**Comment by mvorisek** [comment]
@romaninsh As far as I know this file is specified at least in release script - that is why I marked this PR as draft, drafts should be never merged by someone else.

**Pull request merged**
