### PR TITLE
Simplify use of Persistence\Array_ constructor

### PR DESCRIPTION
**Pull request by mvorisek**
merge after https://github.com/atk4/data/pull/600

### CODE REVIEW

**Review by DarkSide666 — APPROVED** [review]

**Comment by DarkSide666** [comment]
Tests still fail for various reasons.

**Comment by mvorisek** [comment]
@ibelar can you fix Travis? Failing probably because of this change: https://github.com/atk4/data/pull/600

Manipulation of `\$_SESSION` thru `Persistance\Array_` is/was wrong as it does not covered all related settings - now no longer supported by pass any array by reference at all.

**Comment by ibelar** [comment]
> @ibelar can you fix Travis? Failing probably because of this change: [atk4/data#600](https://github.com/atk4/data/pull/600)

@mvorisek - Done!

**Comment by mvorisek** [comment]
@ibelar Perfect, thanks!

**Pull request merged**
