### PR TITLE
add commented example for quicksearch - how to search on each keypress

### PR DESCRIPTION
**Pull request by DarkSide666**
add commented example for quicksearch usage - how to search on each keypress

### CODE REVIEW

**Comment by DarkSide666** [comment]
Maybe `autoChange` method could be useful in this case too.
Let's see what @ibelar will say about that.

**Comment by romaninsh** [comment]
@ibelar i don't like the keystroke. If i type aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa it will query server 30 times. Also you have navigational keys. This should be quite simple really - set timer 0.5sec by default after keystroke and if nothing was pressed in this time, trigger "onchange" early.

This method is simple but was doing wonders. What do you think?

**Comment by DarkSide666** [comment]
I think it should be option there and allow developer to choose what should trigger action:
- only pressing Enter (default)
- onChange event (when you loose focus for example, or - see next one)
- on each keystroke (+ timeout to debounce required here always) - fires onChange (see above)

Probably last two options are actually the same - _trigger action on change_ (same as keystroke in this implementation)

**Comment by romaninsh** [comment]
closing in favour of #563

**Pull request closed without merging**
