### PR TITLE
Upgrade Fomantic UI to 2.8.5

### LINKED ISSUE #992: Improve UX - Add arrow to all/between Wizard items
image

With arrows the Wizard components seems much more understandable to me (/w arrows = wizard, /wo = menu). Wdyt?

### LINKED ISSUE #1044: Tabs with wrong default active tab
In the most recent version, the tab view chooses automatically the last tab as the default active tab. Prior behaviour was the first tab which makes more sense.

### PR DESCRIPTION
**Pull request by mvorisek**
Reopen of PR #979 as this PR was reverted by #1049 

fixes #992
fixes #1044

### CODE REVIEW

**Comment by ibelar** [comment]
@mvorisek - what is the point of reopening this? The Fomantic-UI release use in this pr is problematic with tabs and will always be. Furthermore, it can get merged by accident like the last time.

**Comment by mvorisek** [comment]
@ibelar I created it as a draft request so it can not :)

And now I also bolded the note to not merge it + added WIP to the title.

The point is that some issues were linked to the previous PR and closed with the merge. Now all issues with older Fomantic UI versions can be linked against this. Does it make sense?

**Comment by romaninsh** [comment]
lets leave the version updates to @ibelar - whenever suitable / appropriate.

**Comment by mvorisek** [comment]
@ibelar new/fixed Fomantic was released, see https://github.com/fomantic/Fomantic-UI/releases and https://github.com/fomantic/Fomantic-UI/pull/1488/files

downgrade was more than one version change, see https://github.com/atk4/ui/pull/1049/files , please test and update this PR if more changes are required

**Comment by ibelar** [comment]
Replace by #1240

**Pull request closed without merging**
