### PR TITLE
Use ::addTo() method in View::add()

### LINKED ISSUE #907: Huge improve in autocomplete / refactoring / usability for programmers - return specific type instead of generic one
A lot of code constructs look like:
```
$form = $app->add('Form');
```

in better case there is an extra type hint like:
```
use atk4\ui\Form;

/* @var $form Form */
$form = $app->add('Form');
```

This is a feature request to add `__construct` option `addTo` (and maybe some generic option for things like `addField`) like:
```
use atk4\ui\Form;

$form = new Form(['addTo' => $app]);
```
which should be equivalent of `$form = $app->add('Form');`.

This will hugely improve utocomplete / refactoring / usability for programmers.

All usages and examples should be converted to the new syntax.

`$app->add('Form')` syntax should be dropped in the new 2.x branch and only `$app->add($obj)` should be supported. We should aim step by step for 100% refactorability.

### PR DESCRIPTION
**Pull request by mvorisek**
Fixes #907 , no BC break

Example usage:
```
$crud = \atk4\ui\CRUD::createAndAdd($app); // phpdoc return type = atk4\ui\CRUD
$crud->displayFields = ['name']; // type-hinting work
```

code is equivalent to:
```
$crud = $app->add(\atk4\ui\CRUD::class); // phpdoc return type = atk4\ui\View
$crud->displayFields = ['name']; // type-hinting does not work
```

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
Huge thumbs up for changing the code this way. It actually never really bothered me until I started thinking about your proposal. Will do so much good in combination with a powerful IDE like PHPStorm.

**Comment by romaninsh** [comment]
I've created this: https://github.com/atk4/core/pull/123/files

**Comment by abbadon1334** [comment]
@mvorisek 
> ```php
> $crud = $app->add(\atk4\ui\CRUD::class); // phpdoc return type = atk4\ui\View
> $crud->displayFields = ['name']; // type-hinting does not work
> ```
FYI With this syntax the return type can be rewrite in PhpStorm using .phpstorm.meta.php file
https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/
In this case syntax must be always the same, because from what i see array and simple arguments can't be mixed, IMHO the freedom of writing code in php and atk "conflicts" with some strict rules of defining things in editor, which is legit :(

Defining an interface i think solve only partially the issue, IMHO the only way to solve this would be adding a method for every possible sub-component with the corresponding return type, but this means a big addiction of one line methods, :-1:  i follow the quote "More code, more troubles".

At now all major editor work perfectly like this : 
```php
/** @var Crud $crud */
$crud = $app->add(\atk4\ui\CRUD::class);
$crud->displayFields = ['name']; // type-hinting will work
```

I don't know what can be the best solution.

**Comment by mvorisek** [comment]
@abbadon1334 The magic is to HINT type `static` which is already supported by Netbeans and other IDEs. RETURN of type `static` is expected to be added to PHP 8.0.

HINT = phpdoc
RETURN = type checked by PHP

There is no possibility to return particular type without a static method or generics which is not supported by PHP nor phpdoc.

**Review by abbadon1334 — CHANGES_REQUESTED** [review]
need at least a unit test for static method, but i like the static method and codeintel for the return value. GJ @mvorisek

**Comment by romaninsh** [comment]
ATK Core PR has been merged, so I'm closing this. @mvorisek - thanks for this great suggestions. Lets keep this as an alternative code.

https://github.com/atk4/core/pull/123

**Comment by mvorisek** [comment]
@romaninsh I have this in my todo list, but currently I am out of time. The merged code is not fully ok - for example it hints `self` instead of `static` which almost destroy 50% of its magic ;-)

This PR is actually very hand crafted to support type validation - see https://github.com/atk4/ui/pull/929/files#diff-94ba2466eb979e1b8ba97278c547793aR47 - and I think it is more than required as it can catch a lot of errors and I managed to make it fully compatible with existing code (any `->add` method can be rewriten to it). Wdyt about adding the `$seedExclClassName` parameter directly to the new add trait in `atk4/core`?

I can propose the code, but probably no sonner than 2. Mar.

**Comment by mvorisek** [comment]
Work in progress

**Comment by mvorisek** [comment]
Related work:
- https://github.com/atk4/ui/issues/930
- https://github.com/atk4/ui/issues/989

**Pull request merged**
