### PR TITLE
Feature/demo for 514

### PR DESCRIPTION
**Pull request by DarkSide666**
test case (demo/form) for #514.

See dropdown field "Likes".

### CODE REVIEW

**Comment by romaninsh** [comment]
is that adding demo for a problem? in that case we should keep this open and then include fix and merge.

**Comment by ibelar** [comment]
@DarkSide666 - Not sure what the problem is. The dropdown field is enclosed in a 'Two Wide' css rule  because of the 'width' property being set to two.

The 'two wide' css rule from semantic restricted the width of all elements inside that container to be 12.5%. For sure, dropdown element will not look nice. 

In order to overcome this and make dropdown items look nice, then items element will need to be placed outside that container, probably with absolute positioning. This is not how semantic dropdown module is build. 

Maybe we should ask @mayack to take a look at this, css wise, because I do not see an easy way to fix this without hacking semantic dropdown module.

**Comment by romaninsh** [comment]
@DarkSide666 could it be that your "demo" breaks but it's how it is supposed to be?

**Comment by romaninsh** [comment]
closing as irrelevant.

**Pull request closed without merging**
