### PR TITLE
[FEATURE] introduce autocomplete dependency

### PR DESCRIPTION
**Pull request by georgehristov**
- introduce multiple selection
- introduce dependency handling
- introduce `renderRowFunction`
- cleanup code
- add demos
- update docs

### CODE REVIEW

**Comment by romaninsh** [comment]
Regarding [feature] in the title there is better way:

Modifying this would allow to create universal label throughout all ATK repositories:


https://github.com/atk4/infrastructure/blob/master/projects/agiletoolkit.org/github/agiletoolkit.org/addon/addon-repo.tf#L53

see also https://www.terraform.io/docs/providers/github/r/issue_label.html

And then labels can be used here:
https://github.com/atk4/ui/blob/develop/.github/release-drafter.yml#L3

and they would be properly grouped here: https://github.com/atk4/ui/releases

**Review by romaninsh — APPROVED** [review]

**Review by DarkSide666 — APPROVED** [review]
Looks good to me.
One thing I don't understand is how this goes together with Lookup and DropDown classes. I mean - AutoComplete was meant to be kind of deprecated class in favor of Lookup I think.
@ibelar what you think about this?

**Review by mvorisek — APPROVED** [review]
@georgehristov, perfect work!

**Comment by ibelar** [comment]
Excellent job! I believe that dependency implement here is easier to use than actual Lookup input.

**Comment by mvorisek** [comment]
> I believe that dependency implement here is easier to use than actual Lookup input.

What do you mean exactly?

**Comment by mvorisek** [comment]
> I believe that dependency implement here is easier to use than actual Lookup input.

@ibelar What do you mean exactly?

**Pull request merged**
