### PR TITLE
Fix/Clear Api Data with all server response

### PR DESCRIPTION
**Pull request by ibelar**
Fix: #902

### CODE REVIEW

**Comment by mvorisek** [comment]
The issue will still be presented if 2nd request will be send before the 1st one is returned.

The serialized data should be cleared no later before the request is dispatched (and this is expected to be done in one shot without any context switch).

**Comment by ibelar** [comment]
> The issue will still be presented if 2nd request will be send before the 1st one is returned.

Not really. Fomantic Api is implemented as jQuery plugin which means that each form will have there own data instance object attached to them. successTest will properly clear them for each request. The problem we had before is that when server response was an error,  api.data was not clear for that instance.

**Comment by mvorisek** [comment]
@ibelar And if for some reasons we serialize the same form before the request is returned?

**Comment by ibelar** [comment]
> @ibelar And if for some reasons we serialize the same form before the request is returned?

Can you explain a little more? Not sure what is your use case here.

**Comment by mvorisek** [comment]
@ibelar Currently there is an issue, when the server reponse is not successful, the data are not cleared. Based on the fix I see the issue of bad data will remain if the form is resent before the 1st response has returned.

**Comment by ibelar** [comment]
> @ibelar Currently there is an issue, when the server reponse is not successful, the data are not cleared. Based on the fix I see the issue of bad data will remain if the form is resent before the 1st response has returned.

If the same form is resend prior to receiving its first server response, then fomantic api module will abort the first request. It will also properly clear api.data.

On the other end, if sending multiple forms simultaneously then each form will create its own api request and have their own api.data attach. This fix will properly clear each one of them.

**Comment by mvorisek** [comment]
> If the same form is resend prior to receiving its first server response, then fomantic api module will abort the first request. It will also properly clear api.data.

If so, then this PR is perfect!

**Pull request merged**
