### PR TITLE
fix property names

### PR DESCRIPTION
**Pull request by DarkSide666**

### CODE REVIEW

**Comment by mvorisek** [comment]
I think actions were renamed to userActions. for @georgehristov

**Comment by DarkSide666** [comment]
No they are not, just method names have changed.
This is just a typo fix for *current* develop version because property is named `action` not `actions`.

**Comment by mvorisek** [comment]
seems so, but I have nothing to say to this - @georgehristov may, or just be sure and merge it on your own credit :)

**Review by georgehristov — APPROVED** [review]
Thanks!

**Pull request merged**
