### PR TITLE
Add data field ui parameter for Money to override ui_persistence currency and currency_decimals

### PR DESCRIPTION
**Pull request by stokkeland**
This allows using a parameter in Data Field ui property to override ui_persistence for currency and currency_decimals property, so that applications can use mixed currency presentations within the same rendering. 
Also added docs/ui_persistence.rst documentation, which is not complete, it lists all the properties of ui_persistence and explains most of them, and full example of the features in this enhancement. The rst file was added to toc in Core Concepts under Type Presentation

Simple use:

``` php
$model->addFields([

    // Local cost is exact and uses defaults
    ['local_cost', type => 'money'],

    // Foreign cost is an estimate, uses no fractions and sets currency prefix
    [
        'estimated_cost_norway',
        'type' => 'money',
        'ui' => [
            'persistence' => [
                'currency' => 'NOK',
                'currency_decimals' => 0
            ]
        ]
    ],

    // Energy unit cost is usually very accurate
    ['energy_kw_price', 'type' => 'money', 'ui' => ['persistence' => ['currency_decimals' => 4 ]]]

]);

```

Typical use case of new feature explained here.

Drag a SCREENSHOT here:
image

 - Documentation: [docs/ui_persistence.rst](docs/ui_persistence.rst)
 - I did not create a demo. I will do that another day.

I be happy to re-works some of this if a different structure is preferred in ui property or similar - i figured some documentation is better than none

### CODE REVIEW

**Comment by stokkeland** [comment]
i see the styleci wanted one extra space line for space - something i would normally do but the document was lacking spacing throughout the switch/case statement so I was keeping it the same.  if re-doing anything i'll work out better spacing for the whole switch block.

I do not know what the codecov items means - anyone familiar with the UI class can probably look at this and figure out it is sane code.

The only thing in question, which i tried to ask in the gitter channel but got no respones, is what the proper structure of ui property is in model. I picked what made sense to me.

**Comment by abbadon1334** [comment]
@stokkeland even on yours fork, when you open a PR open with a different branch, give it a meaningful name like : feature/currency-decimal, don't use develop or master or a name already present in the atk4/{repo}/*branches* will give problem on merging

**Comment by stokkeland** [comment]
> ...open a PR open with a different branch...don't use develop or master or a name already present...
Ah okay, yes will do. If desired we can kill this one and i can submit again?

**Comment by abbadon1334** [comment]
> 
> 
> > ...open a PR open with a different branch...don't use develop or master or a name already present...
> 
> Ah okay, yes will do. If desired we can kill this one and i can submit again?

Do it, close this and put that on review to let others check it.

**Comment by stokkeland** [comment]
Okay closing this and will re submit - it may be a few days as I am the middle of another sprint. Btw, I could never find a way to request review.

**Pull request closed without merging**
