### PR TITLE
Cleanup coverage testing

### PR DESCRIPTION
**Pull request by mvorisek**
Not sure why there was a `sleep` command - if some files are flushed not immediatelly (like from webserver, we should cleanly shutdown the process first).

Before:
image

After:
image

### CODE REVIEW

**Comment by mvorisek** [comment]
The `sleep` is there intentionally - coverage decreased even if it should not - please advise how to cleanly restart the webserver before coverage analysis - this should fix the issue.

**Comment by abbadon1334** [comment]
if i remember correctly behat needs some time to initialize

**Comment by mvorisek** [comment]
> 
> 
> if i remember correctly behat needs some time to initialize

Behat is called before the `sleep`.

**Comment by abbadon1334** [comment]
> > if i remember correctly behat needs some time to initialize
> 
> Behat is called before the `sleep`.

if i remember correctly, behat starts and cannot be called immediatly for that there was a sleep after start.

**Review by abbadon1334 — APPROVED** [review]
i like this solution

**Review by romaninsh — COMMENTED** [review]
Thanks!

**Pull request merged**
