### PR TITLE
Add filtering possibility for `float` and `atk4_money` DBAL types

### PR DESCRIPTION
**Pull request by mkrecek234**
Please add these missing filters for table columns

### CODE REVIEW

**Comment by mvorisek** [comment]
I prefer to register `TypeNumber` class to handle the float/atk4_money types instead.

**Comment by mkrecek234** [comment]
It auto-references the Filter today towards FilterAtk4_money, so in case this is missing, no filtered grid will work. I would prefer to include by now, so grid supports any field type and is not throwing errors.

**Comment by mvorisek** [comment]
@mkrecek234 please test

**Comment by mkrecek234** [comment]
@mvorisek Tested and working👍

**Pull request merged**
