### PR TITLE
Use also different actual name

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Review by georgehristov — APPROVED** [review]

**Comment by mvorisek** [comment]
@georgehristov seems atk4/data does not resolve their_field etc. correctly (using model's `actual`). Would you like to help with this?

**Comment by georgehristov** [comment]
@mvorisek yes, I will have a look

**Comment by mvorisek** [comment]
@georgehristov or drop `actual` completely? (with hintable, why do we need it at all?)

**Review by DarkSide666 — APPROVED** [review]
ok

**Comment by mvorisek** [comment]
@georgehristov @DarkSide666 this data bug should be fixed asap, can you help with the fix?

**Pull request merged**
