### PR TITLE
Remove support of relative class names

### PR DESCRIPTION
**Pull request by mvorisek**
Relative names are absolutely no longer needed when classes are referred by `::class` expr.

This PR removes the deprecated behaviour. It breaks BC, but it prevent bad use of unrefactorable classes which is stronger.

To fix your projects check the results of regex (for bests result use case-sensitive matching mode and do in the order like here):

- `atk4\ui\FormLayout\Section` (used only with `->addSubLayout()`)
   ```
   ['"]([^'" ]+\\)?(Accordion|Columns|Generic|Tabs)['"]
   ```
- `atk4\ui\FormLayout`
   ```
   ['"]([^'" ]+\\)?(_Abstract|Columns|Custom|Generic)['"]
   ```
- `atk4\ui\Layout`
   ```
   ['"]([^'" ]+\\)?(Admin|Centered|Column|Generic|Maestro|Navigable|Product)['"]
   ```
- `atk4\ui\FormField`
   ```
   ['"]([^'" ]+\\)?(AutoComplete|DropDownCascade|Hidden|Lookup|Password|TreeItemSelector|Calendar|DropDown|Input|Money|Radio|UploadImg|CheckBox|Generic|Line|MultiLine|TextArea|Upload)['"]
   ```
- `atk4\ui`
   ```
   ['"]([^'" ]+\\)?(Accordion|HelloWorld|jsNotify|Locale|Table|AccordionSection|Console|Icon|jsPaginator|LoremIpsum|Tab|CRUD|Image|jsReload|Menu|Tabs|App|DropDownButton|Item|jsSearch|Message|TabsSubView|BreadCrumb|DropDown|ItemsPerPageSelector|jsSortable|Template|Button|jQuery|jsSSE|Modal|Text|CallbackLater|Exception|jsCallback|jsToast|Paginator|View|Callback|jsChain|jsVueService|VirtualPage|CardDeck|jsConditionalForm|jUniv|Wizard|Card|Form|jsExpressionable|Label|Popup|CardSection|GridLayout|jsExpression|ProgressBar|CardTable|Grid|jsFunction|Lister|Step|Columns|Header|jsModal|Loader|TableColumn)['"]
   ```

### CODE REVIEW

**Comment by mvorisek** [comment]
Coverage is not changed at all - https://codecov.io/gh/atk4/ui/pull/1158/changes

**Comment by mvorisek** [comment]
@romaninsh legit?

**Comment by romaninsh** [comment]
Agree with @mvorisek - it's an old and bad coding style, should probably be dropped in favour of namespaces.

**Comment by romaninsh** [comment]
@mvorisek - could this be implemented with a "warning" at first ? through a logger mechanics.

**Comment by mvorisek** [comment]
> could this be implemented with a "warning" at first ? through a logger mechanics.

@romaninsh It can, but you will not gain anything except error in a different format, I think the best ways to update your code is to list all your classes and then search for `'([^']+\\)?(short_name_1|short_name_2|...)'` and fix all results represention a class (as it may be regular string)

**Review by DarkSide666 — APPROVED** [review]
Probably this will break quite a lot of projects, but ... yeah, this is right way to do things so _let's go_ with it.

Also it would be good if you could add this regex you mentioned somewhere in release notes so developers can use it when refactoring their projects on newer toolkit version.

**Comment by mvorisek** [comment]
> this regex

I will do shortly, 👌

**Pull request merged**
