### PR TITLE
Lint (incl. CS) JS files in GH CI

### LINKED ISSUE #1406: CRITICAL: (ui) tab reloads when opening link to a new (browser) tab
Steps to reproduce:
1. I am on `/interactive/tabs.php`
2. I press and hold ctrl + click on left menu item (like `Interactive -> Card` item)
3. it should open that item in a new (browser) tab
4. now - notice - that the current (ui/demo) tab (`Default Active Tab`) reloads (notice loader icon for a short time)

expected - no (ui/demo) reload, only a new (browser) tab must open

### PR DESCRIPTION
**Pull request by mvorisek**
also fixes #1406

### CODE REVIEW

**Comment by ibelar** [comment]
> @ibelar can you please resolve the Lint issues?

@mvorisek - Ok I will take a look this week.

**Comment by ibelar** [comment]
fix #1406

**Comment by mvorisek** [comment]
@ibelar great, let's merge this

Originally I added AirBNB CS rules as there are much stricter - can you fix the issues as well? I prepared another PR for it - https://github.com/atk4/ui/pull/1426

**Review by georgehristov — APPROVED** [review]
LGTM

**Pull request merged**
