### PR TITLE
Add return type hint

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
Hi, if it always returns a FormField\Generic, why not use type hinting like
`public function getField($name): Generic` ? I think thats way better than only a comment.

**Comment by mvorisek** [comment]
@PhilippGrashoff  I agree, I will amend this PR, I was not sure if this is ok as atk4 has very loose type checking.

**Comment by PhilippGrashoff** [comment]
As far as I understood thats one thing thats constantly improved :)

**Comment by DarkSide666** [comment]
And no more `@return FormField\Generic` typehint? :(

**Comment by mvorisek** [comment]
> And no more `@return FormField\Generic` typehint? :(

Yes, this is new industry standard practice to not write phpdoc without any extra meaningfull info.

The same for typed parameters without description. (same again, no extra info, the phpdoc only occupies space)

This is also default behaviour of CS fixer with default rules and probably also advised by PSR-12.

**Pull request merged**
