### PR TITLE
Test generated JS/CSS files in CI

### PR DESCRIPTION
**Pull request by mvorisek**
Very important generated files match the source code.

`--compatibility=ie8` not needed if support for IE10 is enough (it should be in y2020).

### CODE REVIEW

**Comment by mvorisek** [comment]
@ibelar do you know why tte tests - https://github.com/atk4/ui/pull/1162/checks?check_run_id=638691856#step:9:42 is failing?

**Comment by romaninsh** [comment]
as per @ibelar - source files of a bundle are not in repository. Please allow us to review this situation carefully - blocking PR for now.

**Comment by ibelar** [comment]
@mvorisek - Not sure why the js bundle is include in this PR without package source code? If it is a mistake from your side, please remove the js bundle from this pr. Being able to push the bundle directly is prohibited. If you need to change something at the js package, then only includes source code.

**Comment by mvorisek** [comment]
@romaninsh @ibelar wdym? I just compiled the current sources, the minified js was not in sync. Ok to merge to so?

**Comment by ibelar** [comment]
@mvorisek - It is @romaninsh that put the BLOCKED label. So my advice would be to not remove it again. We need to fix somethings in repo prior to go with this.

**Comment by mvorisek** [comment]
> 
> 
> as per @ibelar - source files of a bundle are not in repository. Please allow us to review this situation carefully - blocking PR for now.

@romaninsh @ibelar @DarkSide666  They are, please save my time if you value my work. If you want to keep denying and witholding changes just let me know. I choosed to help with this project as if I have to maintain our fork, I think is easier to help and better overall to fix and improve this project directly. At this point, I would kindly ask you to review and rate my work on this repo and also on other repos. Please let me know what you like and what not.

**Comment by romaninsh** [comment]
@ibelar ui.agiletoolkit.org pipeline is now working again (#1174).

With that we can incorporate necessary NPM builds in demos/Dockerfile. If we structure it correctly (ref saasty/frontend) - we can effectively cache NPM builds.

With a good develop-based reliable CDN, we should be able to drop this file and we won't need releases either.

Will you be able to take it from here?

**Comment by ibelar** [comment]
I will check.

**Comment by ibelar** [comment]
Replace by #1176

**Comment by mvorisek** [comment]
@ibelar 👍 for the new PR, it may be better, I have reacted for the current state, i.e. to incl. the compiled files in this repo. In this PR I proposed also other changes like removing compatibility flag for IE8, wdyt about it?

**Comment by romaninsh** [comment]
Unblocked now - please merge upstream and remove bundles.

**Comment by romaninsh** [comment]
About IE8 compatibility - yes, for sure - get rid of that, it's very old. Thanks!

**Comment by romaninsh** [comment]
https://github.com/atk4/ui/pull/1162/checks?check_run_id=644165524#step:9:57

**Comment by romaninsh** [comment]
@mvorisek @ibelar - closing in favour of https://github.com/atk4/ui/pull/1178

**Pull request closed without merging**
