### PR TITLE
Fix Demo - Crud caption for Anonymous class

### PR DESCRIPTION
**Pull request by abbadon1334**
https://ui.agiletoolkit.org/demos/collection/crud3.php

image

### CODE REVIEW

**Review by ibelar — APPROVED** [review]
Thanks!

**Review by mvorisek — CHANGES_REQUESTED** [review]
Seems this can not be solved differently...

**Review by mvorisek — APPROVED** [review]

**Comment by ibelar** [comment]
@abbadon1334 - Please fix CodeStyling prior to merge.

**Review by mvorisek — CHANGES_REQUESTED** [review]
I think we should at least fix the issue - if class is anonymous, we should use parent class name.

**Comment by ibelar** [comment]
> I think we should at least fix the issue - if class is anonymous, we should use parent class name.

@mvorisek - not sure what you mean here. This anonymous class extend data\Model. You want the CRUD button to display 'Add Model'? I think 'Add Country' is more appropriate.

**Comment by mvorisek** [comment]
> You want the CRUD button to display 'Add Model'?

at least - see https://github.com/atk4/data/pull/633 - please review, then check if it works - and then this can be merged... But test my PR first.

**Comment by ibelar** [comment]
> at least - see [atk4/data#633](https://github.com/atk4/data/pull/633) - please review, then check if it works - and then this can be merged... But test my PR first.

@mvorisek - To be honest, I do not see the necessity of running an extra test in data/Model for this. This anonymous class behaviour would probably be used rarely. All you have to do is change the caption, simple.

**Comment by mvorisek** [comment]
@ibelar I meant to test the PR manually if it works,,,

image

done it by myself now

**Review by mvorisek — APPROVED** [review]

**Pull request merged**
