### PR TITLE
Fix init(), setDefaults(), normalizeClassNameApp() methods headers

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Review by DarkSide666 — CHANGES_REQUESTED** [review]
Please fix:
```
Declaration of atk4\ui\TableColumn\Link::setDefaults(array $properties = Array, bool $passively = false) should be compatible with atk4\ui\TableColumn\Generic::setDefaults($properties = Array, $passively = false)
```

**Comment by mvorisek** [comment]
@DarkSide666 https://github.com/atk4/core/pull/156 need to be merged first

**Comment by DarkSide666** [comment]
still errors:
```
1) atk4\ui\tests\DemoCallExitExceptionTest::testDemoHTMLStatusAndResponse with data set #46 ('layouts_manual.php')
RegExp error on layouts_manual.php
...
```

**Comment by mvorisek** [comment]
@DarkSide666 fixed

**Review by DarkSide666 — APPROVED** [review]
LGTM now

**Pull request merged**
