### PR TITLE
Atk4/ui/feature/tabs selected tab

### PR DESCRIPTION
**Pull request by skondakov**
Integrate selected tab feature for tabs control

``` php
$tabs->addTab('tab name', null, [true if you want to set this tab as selected, default is false]);
..
```

### CODE REVIEW

**Comment by DarkSide666** [comment]
Looks good to me, but not sure if it's good to add this as 3rd parameter. Maybe we should better use seed mechanism for consistency? Something like `$tabs->addTab('tab name', ['active' => true])`

**Comment by romaninsh** [comment]
i also thought - seeds, but our tabs don't have a predictable way to reference them. The only other way is 

$t->addTab('..')->makeActive().

@DarkSide666 , @ibelar your thoughts on this?

**Comment by ibelar** [comment]
makeActive() method sounds good. 
We could also probably use this method definition to enable loading of dynamic tab when made active. As of now, if a dynamic tab is add and set active, it is not loading dynamic content automatically. User still need to click Tab to load content.

**Comment by romaninsh** [comment]
yes this PR should accommodate dynamic tabs also.

**Comment by DarkSide666** [comment]
`makeActive()` sounds good and surely it should also fix dynamic tabs (automatic loading of them when made active).

**Comment by skondakov** [comment]
I agree with all of you guys. 

- Refactored the feature to work with method setActive() after adding a tab.
- Fixed problem with dynamic tabs - loading when a tab is selected
- Added example in demo

**Pull request merged**
