### PR TITLE
[fix] - Downgrade Fomantic-UI release to 2.7.4

### LINKED ISSUE #1044: Tabs with wrong default active tab
In the most recent version, the tab view chooses automatically the last tab as the default active tab. Prior behaviour was the first tab which makes more sense.

### PR DESCRIPTION
**Pull request by ibelar**
Going back to a atk4/tab friendly Fomantic UI release.

fixes : #1044, #1043

### CODE REVIEW

**Review by mvorisek — DISMISSED** [review]
Are we under pressure to solve things by downgrading?

I would highly prefer to keep the latest stable version and solve the real issues. It is also important when others (and we count to them) are using atk with 3rd party frameworks/components that also use Fomantic UI - only by fixing the issues we can ensure compatibility with the latest stable version that should be supported by `develop` branch.

**Comment by DarkSide666** [comment]
Not sure what exactly you mean @mvorisek .

Latest release of Fomantic contain bug. We're not sure when they will solve it, so we have to roll back or Fomantic issue will become our UI issue of our stable branch.

**Review by DarkSide666 — APPROVED** [review]
I think we need this while Fomantic don't fix their bug and make new, more stable release.

**Comment by mvorisek** [comment]
> Latest release of Fomantic contain bug.

@DarkSide666 Can we fix it from atk side?

**Comment by mvorisek** [comment]
> Sorry but we do not have any control on Fomantic UI release. Bug is in there package.. We need to downgrade their release version for our Tabs to work.

Please link that bug to the issue #1044.

Can we fix this bug with Javascript? Is there any other major issue that prevent us to keep the new version?

**Comment by DarkSide666** [comment]
@mvorisek Is there something we really, really need in that new Fomantic release? If no, then I don't see a problem to use 2.7.4. If there are a lot of cool features which we could use in atk UI, then ... at this point still - use 2.7.4 because it works :)
Maybe it's possible to make some JS workaround, but why would @ibelar spend time on that?

**Comment by mvorisek** [comment]
@DarkSide666 almost one year of fixes https://github.com/fomantic/Fomantic-UI/releases :) The important ones are for dropdown and modal components. So the latest FUI version can save us all a lot of time not figuring out bugs that are already fixed.

**Comment by DarkSide666** [comment]
Ok. Let @ibelar check if he can work around that tab issue somehow.

**Comment by ibelar** [comment]
Sorry guys, can't do much on this one but wait for Fomantic-UI to fix this. The problem is from the new Tab feature introduced in 2.7.8 when they are initialized. They are aware of the situation. (see https://github.com/fomantic/Fomantic-UI/issues/1255) Not exactly the same issue but caused by the same code. I have also discussed the problem with Lubber from Fomantic UI and he is aware of our situation.

My suggestion is to revert to release 2.7.4 - and those who need a higher release can change it in their app manually. This way our tab and behat test our back to normal.

**Comment by lubber-de** [comment]
I proposed a quick solution in Fomantic by adding a new option which, if disabled, will skip the autodetection of an active tab, so the old behavior will be used.
https://github.com/fomantic/Fomantic-UI/issues/1255#issuecomment-636092402

**Pull request merged**
