### PR TITLE
fomantic update 2.8.4

### LINKED ISSUE #992: Improve UX - Add arrow to all/between Wizard items
image

With arrows the Wizard components seems much more understandable to me (/w arrows = wizard, /wo = menu). Wdyt?

### PR DESCRIPTION
**Pull request by romaninsh**
Updating fomantic version.

Fixes #992

### CODE REVIEW

**Comment by ibelar** [comment]
@romans - Title say update to 2.8.4 but the change is for 2.7.4 Not sure which one is correct.
Also note that atk4/ui Tabs are not working starting from Fomantic version 2.7.8, so updating to 2.8.4 will cause a problem. Still need to check with them what is best solution to fix it.

**Comment by romaninsh** [comment]
🤦‍♂ fixed now.

**Comment by DarkSide666** [comment]
This PR should include necessary fixes for Tabs and some testing should also be done.

**Comment by mvorisek** [comment]
Fixes #992

**Pull request merged**
