### PR TITLE
The default function should return as it is

### PR DESCRIPTION
**Pull request by gowrav-vishwakarma**
but it is returning void and that breaks demos app where in init.php you use default App.

The correct way to leave the empty function is to return what is received in params.

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
I am wondering if this function should be implemented with any functionality at all in vanilla atk. As normalizeClassName() first checks for a result from this function and exits afterwards, nearly all functionality of normalizeClassName is not executed at all.

**Review by DarkSide666 — CHANGES_REQUESTED** [review]
Should be at least `return $prefix.'\\'.$name;` but even then I'm not sure if this is needed.
See @PhilippGrashoff comment above.

**Comment by romaninsh** [comment]
no this is wrong - new implementation of the method must return "null" for the default resolution method to work.

**Comment by romaninsh** [comment]
also - travis has lots of errors because of this fix.

**Pull request closed without merging**
